// Nonvisual integration check. No screenshots, video, or gameplay appearance review.
// Uses the browser dependency installed with the sibling official recipe checkout.
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { pathToFileURL } from 'node:url';
const requireRecipe = createRequire(new URL('../../recipe/package.json', import.meta.url));
const puppeteer = (await import(pathToFileURL(requireRecipe.resolve('puppeteer')).href)).default;
const browser = await puppeteer.launch({ headless: true, args: ['--enable-unsafe-swiftshader'] });
const errors = [];
try {
  const page = await browser.newPage();
  page.on('pageerror', e => errors.push(e.message));
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
  await page.goto(process.argv[2] || 'http://127.0.0.1:4173/');
  await page.waitForFunction(() => window.__READY__);
  await page.click('#tune-toggle'); await page.click('#invincible'); await page.click('#tune-close');
  await page.click('#startb');
  await page.keyboard.down('ShiftLeft');
  await page.waitForFunction(() => window.__GAME__.racingHeld && window.__GAME__.speed > 65);
  assert.equal(await page.evaluate(() => window.__GAME__.boostEnergy), 100);
  await page.keyboard.down('ControlLeft');
  await page.waitForFunction(() => window.__GAME__.braking && !window.__GAME__.racingHeld && window.__GAME__.speed < 14);
  await page.keyboard.up('ControlLeft');
  await page.waitForFunction(() => window.__GAME__.racingHeld);
  await page.keyboard.down('Space');
  await page.waitForFunction(() => window.__GAME__.boosting && window.__GAME__.speed > 95 && window.__GAME__.boostEnergy < 99);
  await page.keyboard.up('Space');
  await page.waitForFunction(() => !window.__GAME__.boosting && window.__GAME__.racingHeld);
  await page.keyboard.up('ShiftLeft');
  await page.waitForFunction(() => !window.__GAME__.racingHeld && window.__GAME__.speed < 30);
  await page.keyboard.press('r');
  await page.keyboard.down('w');
  await page.waitForFunction(() => window.__GAME__.offset > 1 && window.__GAME__.speed < 27 && !window.__GAME__.racingHeld);
  await page.keyboard.up('w'); await page.keyboard.down('s');
  await page.waitForFunction(() => window.__GAME__.offset < 0.5 && !window.__GAME__.braking);
  await page.keyboard.up('s'); await page.keyboard.down('Space');
  await page.waitForFunction(() => window.__GAME__.boosting);
  await page.keyboard.press('p');
  await page.waitForFunction(() => window.__GAME__.status === 'paused');
  await page.keyboard.up('Space');
  await page.keyboard.press('p');
  await page.waitForFunction(() => window.__GAME__.status === 'playing' && !window.__GAME__.racingHeld && !window.__GAME__.boosting);

  await page.setViewport({ width: 390, height: 844, isMobile: true, hasTouch: true });
  await page.reload(); await page.waitForFunction(() => window.__READY__);
  await page.click('#tune-toggle'); await page.click('#invincible'); await page.click('#tune-close');
  const center = selector => page.$eval(selector, e => { const r = e.getBoundingClientRect(); return { x: r.x + r.width / 2, y: r.y + r.height / 2 }; });
  const start = await center('#startb'); await page.touchscreen.tap(start.x, start.y);
  const stick = await center('#stick'), boost = await center('#boost-hold');
  const cdp = await page.createCDPSession();
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ ...stick, id: 1 }] });
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: stick.x, y: stick.y - 13, id: 1 }] });
  await page.waitForFunction(() => window.__GAME__.offset > 1 && !window.__GAME__.racingHeld && window.__GAME__.speed < 27);
  const fastFinger = { x: stick.x + 14, y: stick.y - 30, id: 1 };
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [fastFinger] });
  await page.waitForFunction(() => window.__GAME__.racingHeld && window.__GAME__.lateral > 1 && window.__GAME__.speed > 65);
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [fastFinger, { ...boost, id: 2 }] });
  await page.waitForFunction(() => window.__GAME__.boosting && window.__GAME__.speed > 95);
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [{ ...boost, id: 2 }] });
  await page.waitForFunction(() => !window.__GAME__.boosting && window.__GAME__.racingHeld);
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [fastFinger, { ...boost, id: 2 }] });
  await page.waitForFunction(() => window.__GAME__.boosting);
  const brakeFinger = { x: stick.x, y: stick.y + 32, id: 1 };
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [brakeFinger, { ...boost, id: 2 }] });
  await page.waitForFunction(() => window.__GAME__.braking && !window.__GAME__.boosting && window.__GAME__.speed < 14);
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [brakeFinger] });
  await page.waitForFunction(() => !window.__GAME__.braking && !window.__GAME__.racingHeld && window.__GAME__.boostLocked);
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] });
  await page.waitForFunction(() => !window.__GAME__.boostLocked);
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ ...stick, id: 3 }, { ...boost, id: 4 }] });
  await page.waitForFunction(() => window.__GAME__.boosting);
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [{ ...stick, id: 3 }] });
  assert.equal(await page.evaluate(() => window.__GAME__.boosting), true, 'lifting steering finger preserves independently held boost');
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchCancel', touchPoints: [] });
  await page.waitForFunction(() => !window.__GAME__.boosting);
  // Exercise ramp and armored render paths without observing gameplay images.
  await page.setViewport({ width: 1280, height: 800, isMobile: false, hasTouch: false });
  await page.reload(); await page.waitForFunction(() => window.__READY__);
  await page.click('#tune-toggle'); await page.click('#invincible'); await page.click('#tune-close');
  await page.click('#startb'); await page.keyboard.down('ShiftLeft');
  await page.waitForFunction(() => window.__GAME__.armored > 0 && window.__GAME__.distance > 550, { timeout: 30000 });
  await page.keyboard.up('ShiftLeft');
  await page.click('#tune-toggle');
  assert.ok(await page.evaluate(() => window.__GAME__.vehicles > 0), 'neutral traffic is present');
  await page.$eval('#shake', e => { e.value = 0; e.dispatchEvent(new Event('input', { bubbles: true })); });
  await page.$eval('#wind', e => { e.value = 0; e.dispatchEvent(new Event('input', { bubbles: true })); });
  await page.waitForFunction(() => window.__GAME__.options.shake === 0 && window.__GAME__.options.wind === 0);
  await page.click('#tune-close');
  await page.waitForFunction(() => window.__GAME__.status === 'playing');
  assert.deepEqual(errors, []);
  console.log('PASS: WASD repositioning, Shift fast mode, Ctrl brake, Space boost, pause input reset, analog stick zones, two-finger fast/boost/brake, independent release and cancellation, traffic runtime paths, effect controls, and no runtime errors. No visual testing performed.');
} finally { await browser.close(); }
